on:
    push:
      branches:
        - main  # Trigger the workflow on any push to the 'main' branch
  
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Check out the code from the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Set up Node.js (specify the correct Node version)
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'  # Specify your Node.js version

      # Step 3: Install dependencies
      - name: Install dependencies
        run: npm install

      # Step 4: Package the application (create a zip file of the relevant files)
      - name: Zip application files
        run: zip -r application.zip server.js package.json node_modules/  # Adjust the files/directories based on your project structure

      # Step 5: Upload the artifact (optional, can be used for deployment later)
      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: application
          path: application.zip

      # Step 6: Transfer the artifact to the EC2 instance
      - name: Copy artifact to EC2 instance
        uses: appleboy/scp-action@v0.1.3  # Use the latest stable version
        with:
          host: ${{ secrets.EC2_HOST }}     # Your EC2 instance public IP
          username: ${{ secrets.EC2_USER }} # SSH user, e.g., "ec2-user"
          key: ${{ secrets.EC2_SSH_KEY }}   # Private key for SSH access
          source: application.zip           # The artifact to be transferred
          target: /home/csye6225/app/application.zip  # Adjust the target path for the csye6225 user

      # Step 7: SSH into the EC2 instance to configure ownership and start the application
      - name: SSH and Set Ownership + Start Application
        uses: appleboy/ssh-action@v0.1.5
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            sudo chown csye6225:csye6225 /home/csye6225/app/application.zip
            cd /home/csye6225/app
            sudo -u csye6225 unzip application.zip
            sudo -u csye6225 npm install --production
            sudo -u csye6225 npm start  # or your start command
